import { createSlice } from "@reduxjs/toolkit"; // Import the createSlice function from Redux Toolkit

// Define a slice for managing video data
const videoSlice = createSlice({
  name: "videos", // A name for the slice, used to identify its actions and state
  initialState: {
    data: [], // Initial state of the videos, default is an empty array
  },
  reducers: {
    // Reducer to set the video list in the state
    setVideoList: (state, action) => {
      state.data = action.payload; // Updates the state with the provided video list
    },
    // Reducer to clear the video list from the state
    clearVideoList: (state) => {
      state.data = []; // Resets the video list to an empty array
    },
  },
});

// Export the action creators generated by the slice
export const { setVideoList, clearVideoList } = videoSlice.actions;

// Export the reducer to be added to the Redux store
export default videoSlice.reducer;
